services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
    depends_on:
      db: 
        condition: service_started
        restart: false
      redis: 
        condition: service_started
    restart: always 
  db:
    image: postgres
    restart: unless-stopped 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: super-secret-ingredient 
  redis:
    image: redis
    restart: unless-stopped 
