services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: super-secret-ingredient 
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
